version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - misspell
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    paths:
      - .gopath

formatters:
  enable:
    - gofmt
